---
# test-a-thon 2026 modification v3
- name: Simple Rulebook for Demo
  hosts: all
  sources:
    - name: Demo Source
      ansible.eda.generic:
        payload:
          - msg: "Welcome"
          - msg: "Adios"
          - msg: "Hola"
          - msg: "Ciao"
          - msg: "Bonjour"
  rules:
    - name: Say Hello
      condition: event.msg == "Welcome"
      action:
        debug:
          msg: "Hello from EDA - test-a-thon 2026 v3"
...
